version: '3.8'

services:
  # Database Service (PostgreSQL)
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Application Service (FastAPI)
  app:
    build: .
    container_name: duolingo-de-app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      # Mount the local 'app' directory into the container for hot reloading
      - ./app:/code/app
      - ./migrations:/code/migrations
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: