# In app/middlewares.py

import time
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request


class ProcessTimeMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        # Code here runs BEFORE the request reaches the endpoint
        start_time = time.time()

        # call_next(request) passes the request to the endpoint
        response = await call_next(request)

        # Code here runs AFTER the response is generated by the endpoint
        process_time = time.time() - start_time
        print(response)
        response.headers["X-Process-Time"] = str(process_time)

        return response
